project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides/bagian-1.qmd
    - slides/bagian-2.qmd
  resources:
    - _extensions/rameliaz/unair/logo.png
    - _extensions/rameliaz/unair/logo_white.png

website:
  title: "Workshop Publikasi Ilmiah"
  navbar:
    left:
      - href: https://rameliaz.github.io/
        icon: house
        text: "oleh Rizqy Amelia Zein"
      - icon: github
        href: https://github.com/rameliaz/penerbitan
    right:
      - text: "Materi"
        menu:
          - text: "Bagian 1 (html)"
            href: slides/bagian-1.html
          - text: "Bagian 1 (pdf)"
            href: slides/bagian-1.html?print-pdf  
          - text: "Bagian 2 (html)"
            href: slides/bagian-2.html
          - text: "Bagian 2 (pdf)"
            href: slides/bagian-2.html?print-pdf  
      - text: "Tugas Menulis"
        menu:
          - text: "Padlet"
            href: https://padlet.com/ameliazein/berlatih-menulis-xcpa9ybswkvfuvlt
      - text: "Survei"
        menu:
          - text: "Evaluasi Workshop"
            href: https://www.soscisurvey.de/fb-workshop-amel/     
      - icon: github
        href: https://github.com/rameliaz/penerbitan
  
  search:
    location: navbar
    type: overlay
  page-footer:
      left: "&#169; 2026 Rizqy Amelia Zein"
      center: |
        <a class="link-dark me-1" href="https://github.com/rameliaz" title="github" target="_blank" rel="noopener">{{< iconify fa6-brands github >}}</a>
        <a class="link-dark me-1" href=mailto:amelia.zein@psikologi.unair.ac.id title="Email" target="_blank" rel="noopener">{{< iconify material-symbols:mail >}}</a>
        <a class="link-dark me-1" href="https://bsky.app/profile/ameliazein.bsky.social" title="Bluesky" target="_blank" rel="noopener">{{< iconify fa6-brands bluesky >}}</a>
        <a class="link-dark me-1" href="https://discord.com/users/807046335613632555" title="Discord" target="_blank" rel="noopener">{{< iconify fa6-brands discord >}}</a>
        
      right: |
        <a class="link-dark me-1" href="https://github.com/rameliaz/tutorial">{{< iconify fa6-brands github >}} Source</a>

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-float: true
    toc-depth: 3
    df-print: paged
    highlight-style: github
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css">
